language: node_js
node_js:
  - node
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE andela_test;" -U postgres
  - psql -c "CREATE USER andela WITH PASSWORD 'andela123';" -U postgres
  - npm run drop
  - npm run create
  - npm run build
script:
  - npm run test
after_success:
  - npm run coverage